# Level 1: Basic Data Review

In [4]:
import pandas as pd

In [5]:
data=pd.read_csv("C:/Users/lavanya/Downloads/Internship_Files/Raw_Dataset.csv")
df=pd.DataFrame(data)
print(df)

        SN  Train_No Station_Code    1A    2A    3A    SL     Station_Name  \
0        1       107          SWV   100   100   100   100     SAWANTWADI R
1        2       107         THVM   260   228   196   164           THIVIM
2        3       107         KRMI   345   296   247   198          KARMALI
3        4       107          MAO   490   412   334   256      MADGOAN JN.
4        1       108          MAO   100   100   100   100      MADGOAN JN.
...     ..       ...          ...   ...   ...   ...   ...              ...
186069   1     22439         NDLS   100   100   100   100        NEW DELHI
186070   2     22439          UMB  1095   896   697  1095   AMBALA CANT JN
186071   3     22439          LDH  1660  1348  1036  1660      LUDHIANA JN
186072   4     22439          JAT  2985  2408  1831  2985       JAMMU TAWI
186073   5     22439         SVDK  3375  2720  2065  3375  SHMATA VD KATRA

        Route_Number Arrival_time Departure_Time  Distance
0                  1     00:00:00       10:25:00         0
1                  1     11:06:00       11:08:00        32
2                  1     11:28:00       11:30:00        49
3                  1     12:10:00       00:00:00        78
4                  1     00:00:00       20:30:00         0
...              ...          ...            ...       ...
186069             1     00:00:00       06:00:00         0
186070             1     08:08:00       08:10:00       199
186071             1     09:19:00       09:21:00       312
186072             1     12:38:00       12:40:00       577
186073             1     14:00:00       00:00:00       655

[186074 rows x 12 columns]

In [6]:
print("Total Number of Rows:",df.shape[0])
print("Total Number of Columns:",df.shape[1])
print("Columns Name:",df.columns.tolist)
print("Basic Information of Dataset: \n")
df.info()
print("Statistical Summary of Numeric Columns:\n")
df.describe()
print("Columns Data Type :\n")
df.dtypes

Total Number of Rows: 186074
Total Number of Columns: 12
Columns Name: <bound method IndexOpsMixin.tolist of Index(['SN', 'Train_No', 'Station_Code', '1A', '2A', '3A', 'SL',
       'Station_Name', 'Route_Number', 'Arrival_time', 'Departure_Time',
       'Distance'],
      dtype='object')>
Basic Information of Dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186074 entries, 0 to 186073
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   SN              186074 non-null  int64
 1   Train_No        186074 non-null  int64
 2   Station_Code    186074 non-null  object
 3   1A              186074 non-null  int64
 4   2A              186074 non-null  int64
 5   3A              186074 non-null  int64
 6   SL              186074 non-null  int64
 7   Station_Name    186074 non-null  object
 8   Route_Number    186074 non-null  int64
 9   Arrival_time    186074 non-null  object
 10  Departure_Time  186074 non-null  object
 11  Distance        186074 non-null  int64
dtypes: int64(8), object(4)
memory usage: 17.0+ MB
Statistical Summary of Numeric Columns:

Columns Data Type :

SN                 int64
Train_No           int64
Station_Code      object
1A                 int64
2A                 int64
3A                 int64
SL                 int64
Station_Name      object
Route_Number       int64
Arrival_time      object
Departure_Time    object
Distance           int64
dtype: object

In [7]:
df.groupby("Train_No")["Station_Code"].agg(Starting_Station="first",Ending_Station="last")

         Starting_Station Ending_Station
Train_No
107                   SWV            MAO
108                   MAO            SWV
128                   MAO            KOP
290                   DSJ            DSJ
401                   AWB            BSB
...                   ...            ...
99904                PUNE            TGN
99905                 TGN           SVJR
99906                PUNE            TGN
99907                 TGN           PUNE
99908                PUNE            TGN

[11113 rows x 2 columns]

In [8]:
df.groupby("Train_No")["Station_Code"].agg(Number_of_Stops="count")

          Number_of_Stops
Train_No
107                     4
108                     4
128                    22
290                    14
401                    12
...                   ...
99904                  12
99905                  11
99906                  12
99907                  12
99908                  12

[11113 rows x 1 columns]

In [9]:
Stops=df.groupby("Train_No")["Station_Code"].agg(Number_of_Stops="count")
Max_Stop=Stops["Number_of_Stops"].max()
Min_Stop=Stops["Number_of_Stops"].min()
print(Max_Stop)
print(Min_Stop)

118
2

In [10]:
Train_With_Max_Stops=Stops[Stops["Number_of_Stops"]==Max_Stop]

In [11]:
Train_With_Min_Stops=Stops[Stops["Number_of_Stops"]==Min_Stop]

In [12]:
print("Maximum_Stop :\t\t",Max_Stop)
print("Train_With_Maximum_Stop \n\n",Train_With_Max_Stops)
print("\nMinimum_Stop :\t\t",Min_Stop)
print("Train_With_Minimum_Stops \n\n",Train_With_Min_Stops)

Maximum_Stop :		 118
Train_With_Maximum_Stop

           Number_of_Stops
Train_No
53041                 118

Minimum_Stop :		 2
Train_With_Minimum_Stops

           Number_of_Stops
Train_No
557                     2
3305                    2
3306                    2
5715                    2
5716                    2
...                   ...
99499                   2
99500                   2
99501                   2
99502                   2
99503                   2

[1249 rows x 1 columns]